### ISSUE TITLE
use the master toolchain on ci?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/glacier#1128]
We could switch glacier to https://github.com/kennytm/rustup-toolchain-install-master and run it perhaps every 6 hours which would find out about fixed ICEs with at finer granularity.

I use the master toolchain in my icemaker crash-finder and I really like it because I don't have to wait up to 24 hours to check new rustc features for ICEs.

**Comment by Alexendoo** [comment]
For me I'd say nightly is fine, also I often end up running `cargo bisect-rustc` if I'm not sure where a fix came from, which is easier to do if the change is in the most recently nightly
