### ISSUE TITLE
Can we already add ICES that need dependencies?

### ISSUE THREAD

**Issue by araruna** [rust-lang/glacier#1223]
I saw a previous issue (#216, from 2019) that needed to add an ICE MWE requiring cargo dependencies. At the time, someone stated that it was not possible. Has anything changed? If so, how should we add such MWEs?

Thank you.

**Comment by JohnTitor** [comment]
Yeah, ICEs containing dependencies would make check time long so I'd like to avoid that (CI could use cache but the same issue happens on contributors, it'd be a pain).
Moreover, on rust-lang/rust repo, we generally mark such an issue as `E-needs-mcve`, which means a repro code should be minimized not to have any deps. So ICEs repros having deps aren't desirable.

I'm going to close this issue in favor of above reasons, but thanks for asking anyway (and contributing)!
