### ISSUE TITLE
Add already-fixed ICEs?

### ISSUE THREAD

**Issue by langston-barrett** [rust-lang/glacier#1527]
The README asks for test cases corresponding to open ICE issues. What about ones that have already been fixed? Might be helpful for #1156 and other purposes (e.g., seeding fuzzing corpora with interesting test cases).

**Comment by Alexendoo** [comment]
For fixed ones the tests usually go in the main rust repo, we usually leave the issues open and mark them E-needs-test if the PR the fixed the ICE didn't add an appropriate test already

**Comment by langston-barrett** [comment]
That makes sense! What about ICE issues that are recently filed and also have an open PR? Should they be left alone since they'll probably be closed soon? Or added in case the fix doesn't land promptly?

**Comment by Alexendoo** [comment]
Yeah those are good to add too, they have occasionally caught a PR that didn't fully fix the issue
