### ISSUE TITLE
Automatically handle fixed ICEs

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/glacier#153]
There should be automation in this repository to automatically handle fixed ICEs. This automation could do:

* [x] Open a PR to remove the fixed ICE from the repository, so a team member can remove it in one click
* [ ] Post a comment on the issue notifying users the ICE has been fixed. Closing the issue automatically could also be investigated

**Comment by Alexendoo** [comment]
I'm working on creating automatic PRs

**Comment by pyfisch** [comment]
isn't this done?

**Comment by JohnTitor** [comment]
@pyfisch

> Post a comment on the issue notifying users the ICE has been fixed.

This isn't resolved so I keep this issue open.

**Comment by pietroalbini** [comment]
Added checkboxes to monitor the progress of this issue.

**Comment by Elinvynia** [comment]
Gonna take a look at this soon-ish, if it has been {X} time and you want to try it yourself poke me for an update.

**Comment by oliviacrain** [comment]
@Elinvynia Hi, did you get a chance to implement this feature? If not, I can take a crack at it!

**Comment by JohnTitor** [comment]
I'm not sure if we should automate the second point, because:
1. We should make sure that ICE is fixed (e.g. is an additional flag needed now?).
1. We should bisect PR(s) that fixed ICE(s).

I usually do these things, and it's noisy a bit if both bot and I leave comments (and I don't think we can do them automatically).

**Comment by JohnTitor** [comment]
So, I'm going to close this issue in favor of my comment. If anyone find a better way, feel free to leave a comment here!
