### ISSUE TITLE
How to add cargo projects

### ISSUE THREAD

**Issue by Julian-Wollersberger** [rust-lang/glacier#216]
I wanted to add [issue 54960](https://github.com/rust-lang/rust/issues/54960), but it has a crate dependency (binary_macros) and thus needs a cargo project. How should I add it to this repo?

I tested if the macro expanded code from `cargo expand` would recreate the ICE, but unfortunately it doesn't, so the crate dependency is needed.

Also that specific ICE is fixed on current sable and nightly anyway, so I would have added it to the `fixed` directory. Or should I propose to just close it?

**Comment by JohnTitor** [comment]
Currently, we cannot add ICEs require dependencies IIRC.

**Comment by Julian-Wollersberger** [comment]
Oh. Anyway, thanks for the response ^^
