### ISSUE TITLE
Allow adding proc macro ICEs

### ISSUE THREAD

**Issue by xfix** [rust-lang/glacier#248]
I don't think it's possible to add proc-macro ICEs like https://github.com/rust-lang/rust/issues/59191.

**Comment by JohnTitor** [comment]
I've not tested yet but we cannot add it even though using `#[crate_type = "proc-macro"]`?

**Comment by xfix** [comment]
Sure, but then you cannot call it, I think?

**Comment by JohnTitor** [comment]
The problem here is that it is not a proc-macro but separate files, I guess? I think we can add it with shell script as a workaround.

**Comment by xfix** [comment]
Okay, that seems reasonable. Created #254.
