### ISSUE TITLE
automatically label beta/stable regression

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/glacier#568]
Just an idea:

Glacier could check ICEs with a nightly, beta and stable and old-stable compiler.
If a tracked issue also crashes the latest stable compiler but not old-stable, automatically add the `regression-from-stable-to-stable` label, etc.

**Comment by JohnTitor** [comment]
As discussed on https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/adding.20labels.20to.20stable-to-stable.20regressions and I commented on https://github.com/rust-lang/glacier/pull/767#pullrequestreview-677916069, I'm going to close this issue.
